# Generated by Django 5.0 on 2023-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnewpet',
            name='pet_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
