# Generated by Django 5.0 on 2024-01-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_data', '0002_alter_addnewpet_pet_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
